services:
  simply_dns_exporter:
    image: apxangels/simply-dns-exporter:latest
    container_name: simply_dns_exporter
    ports:
      - "9116:9116"
    volumes:
      - ./config.yml:/app/config.yml:ro
    restart: unless-stopped
